language: python

services:
  - postgresql

python:
  - "3.3"
  - "2.7"
  - "2.6"

env:
  - DJANGO="https://www.djangoproject.com/download/1.7b1/tarball/"
  - DJANGO="django==1.5.5"
  - DJANGO="django==1.6.2"

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="https://www.djangoproject.com/download/1.7b1/tarball/"

branches:
  only:
    - master

before_install:
 - sudo add-apt-repository -r -y ppa:ubuntugis/ppa
 - sudo apt-get update
 - sudo apt-get remove --purge postgresql-9.1-postgis-2.1 postgresql-9.1-postgis-scripts
 - sudo apt-get install postgresql-9.1-postgis libgeoip1

# command to install requirements
install:
  - pip install $DJANGO
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage coveralls --use-mirrors
  - python setup.py -q install

before_script:
  - psql template1 -c 'create extension hstore;'
  - curl https://raw.github.com/django/django/1.5.5/docs/ref/contrib/gis/install/create_template_postgis-debian.sh | sh
  - createdb -T template_postgis django_hstore
  - createdb django_hstore_psycopg2

# command to run tests, e.g. python setup.py test
script:
  - ./runtests.py --settings=settings_psycopg
  - coverage run --source django_hstore runtests.py

after_success:
  coveralls
